### ISSUE TITLE
Support recent Soss versions

### ISSUE THREAD

**Issue by sethaxen** [arviz-devs/ArviZ.jl#124]
Soss is currently at v0.18.3, but our docs currently only support v0.14. We should update to support v0.18 and ensure that the converter still works. This will involve adding support for Soss's [SampleChains.jl](https://github.com/cscherrer/SampleChains.jl). @cscherrer noted on Slack that some of the SampleChains functionality will be moved into [TupleVectors.jl](https://github.com/cscherrer/TupleVectors.jl), so it's probably best to wait until that has happened to work on this.

**Comment by sethaxen** [comment]
@cscherrer it seems that the example on the readme of Soss.jl does not yet product an object that uses TupleVectors, due to incompatibility with SampleChains v0.4. I get a `MultiChain` that uses `ElasticVector`:
```julia
4000-element MultiChain with 4 chains and schema (σ = Float64, β = Float64, α = Float64)
(σ = 0.195±0.041, β = 0.7921±0.051, α = 9.9287±0.049)
```

Here's my environment:

```julia
(jl_yB2yCS) pkg> st
      Status `/private/var/folders/5c/7l7zjpjj4fs6t31xlh4hjggm0000gn/T/jl_yB2yCS/Project.toml`
  [131c737c] ArviZ v0.5.2
  [eadaa1a4] MeasureTheory v0.6.2
  [754583d1] SampleChains v0.3.1
  [6d9fd711] SampleChainsDynamicHMC v0.1.1
  [8ce77f84] Soss v0.18.3
  [615932cf] TupleVectors v0.1.1
```

**Comment by cscherrer** [comment]
Thanks @sethaxen , I'll check around for version bounds.

The history here is that TupleVectors was originally in SampleChains - I moved it out because it seemed independently useful. Overall, its
- A `MultiChain` is a container that holds several `Chain`s
- A `Chain` is holds a `TupleVector`, plus some other information like RNG state, and transforms needed, etc

**Comment by sethaxen** [comment]
Ah, I see, that makes things a little clearer. I see now that `TupleVector` is being used. e.g.

```julia
julia> chain = SampleChains.getchains(post)[1]
1000-element Chain with schema (σ = Float64, β = Float64, α = Float64)
(σ = 0.243±0.037, β = -0.171±0.057, α = 9.909±0.051)

julia> SampleChains.samples(chain)
1000-element TupleVector with schema (σ = Float64, β = Float64, α = Float64)
(σ = 0.243±0.037, β = -0.171±0.057, α = 9.909±0.051)
```

**Comment by sethaxen** [comment]
What is the official API of SampleChains? As in, what assumptions can be made about the returned values of `SampleChains.getchains`, `SampleChains.samples`, and `SampleChains.info`?

**Comment by cscherrer** [comment]
There's some of this I'm still working through, and I'm open to suggestions for changes. Currently,...
- `getchains` returns a `Vector{<:AbstractChain}`
- `samples` returns a `TupleVector`
- `info` returns a `<: AbstractVector`, one entry for each sample, with a type specific to the current sampler. This gives sampler "internals" that do not affect the semantics of the sample (e.g., weights don't belong here)

I'm on the fence about `getchains`, becuase `get*` operations are usually some kind of indexing. So maybe it should just be `chains`. I avoided that to start because I was doing something like `chains = getchains(....)`

Also, this will all be more complicated when we add support for continuous trajectories, which we'll need to work with [ZigZagBoomerang](https://github.com/mschauer/ZigZagBoomerang.jl)
