### ISSUE TITLE
Prior predictive keyword arg not used in from_mcmcchains

### ISSUE THREAD

**Issue by bgroenks96** [arviz-devs/ArviZ.jl#146]
When using `from_mcmcchains(chain; prior_predictive=prior_pred_chain)`, the prior predictive chain is not stored in the resulting `InferenceData`.

Looking at `mcmcchains.jl`, it's pretty clear why; the keyword arg is listed in the documentation but I don't see it handled anywhere in the code?

**Comment by sethaxen** [comment]
Thanks for the issue! `from_mcmcchains` does handle the `prior_predictive` group, but it only does so if `prior` is also provided, which is not right:

https://github.com/arviz-devs/ArviZ.jl/blob/17f2e7e6957f262ffa04c0fd5155cb8952f4f5e2/src/mcmcchains.jl#L254-L271

I'll push a fix, though it might wait until after the holidays. For now, you can make it work by providing also the `prior` chains, which I assume you also have.

**Comment by sethaxen** [comment]
@bgroenks96 the latest ArviZ release should resolve this issue. Please let me know if it persists.

**Comment by bgroenks96** [comment]
Ok will do. I temporarily stopped using the package, though, because I ran into difficulties with the interface to `InferenceData`. We really need a better way to handle `xarray` from Julia.

**Comment by sethaxen** [comment]
> We really need a better way to handle `xarray` from Julia.

I agree. Unfortunately, wrapping xarray really well essentially involves writing an XArray.jl package that wraps all xarray types, which is beyond the scope of this package, especially since we're working to drop Python as a dependency (see e.g. #128, #130). Unfortunately, there's really no clear best xarray drop-in alternative in the Julia ecosystem yet.

If you have the time, issues documenting the specific problems would be very useful, because I might be able to add simple workarounds that would make this package more useful in the interim.

**Comment by bgroenks96** [comment]
I would also be happy with a pure-Julia `InferenceData` scheme. But I doubt you have time to re-implement the multitude of functionality in xarray, though! I certainly don't...

I actually wanted to take a crack at creating an XArray.jl packge. I already have some code lying around which half-implements a wrapping scheme. I hope that I will soon have some time to work on this... I am really not happy with and constantly bothered by the limitations and instability of DimensionalData.jl, the closest Julia alternative to xarray, at the moment.
